# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Get auth of GCP'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: 'Get GKE Credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{vars.CLUSTER}}
        location: ${{vars.LOCATION}}

    - name: 'Make image and push in Artifact Registry'
      run: |
        ls
        gcloud auth --quiet configure-docker ${{vars.GAR}}
        docker build -t ${{vars.GAR_REPO}}/${{vars.IMAGE}}:latest .
        docker push ${{vars.GAR_REPO}}/${{vars.IMAGE}}:latest