# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{vars.CLUSTER}}
        location: ${{vars.LOCATION}}

    - id: 'docker-credential'
      run: 'gcloud --quiet auth configure-docker'

    - id: 'make-container-image'
      run: 'docker build . --file DOCKERFILE_LOCATION --tag ${{ vars.GAR_REPO }}'
      working-directory: WORKING_DIRECTORY
      
    - id: 'push-image'
      run: 'docker push ${{vars.GAR_REPO}}'